org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin/Android
kotlin.code.style=official
# The iOS targets cannot be built on Linux or Windows. This silences the
# warning about them there.
kotlin.native.ignoreDisabledTargets=true
android.useAndroidX=true

# Reproducible builds for F-Droid.
android.nonTransitiveRClass=true
